In [13]:
import pandas as pd
import datetime

In [39]:
df_bova=pd.read_csv("G:\Trading\K11\Dados HistÃ³ricos\historical_bova.csv",';')
df_ind=pd.read_csv("G:\Trading\K11\Dados HistÃ³ricos\historical_ind.csv",';')
df=df_bova.merge(df_ind,on='Dates')
df['Dates']=df['Dates'].apply(lambda x: datetime.datetime.strptime(x,"%d/%m/%Y %H:%M"))
df['trade']=df['Dates'].apply(lambda x: x.minute)
df['5min']=df['trade'].apply(lambda x: x if x%5==0 else -1)
display(df)
df[df['5min']!=-1].to_excel('trades.xlsx')

C:\Python37\lib\site-packages\IPython\core\interactiveshell.py:3457: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  exec(code_obj, self.user_global_ns, self.user_ns)

,Dates,Open_x,Close_x,High_x,Low_x,Volume_x,Number Ticks_x,Open_y,Close_y,High_y,Low_y,Volume_y,Number Ticks_y,trade,5min
0,2022-01-03 10:09:00,"101,44","101,57","101,61","101,42",15580,71,106365,106485,106540,106355,525,93,9,-1
1,2022-01-03 10:10:00,"101,53","101,79","101,79","101,51",13973,42,106490,106725,106730,106475,350,64,10,10
2,2022-01-03 10:11:00,"101,79","101,8","101,82","101,69",45912,82,106715,106765,106780,106710,285,54,11,-1
3,2022-01-03 10:12:00,"101,77","101,73","101,8","101,7",152559,65,106765,106695,106775,106685,855,157,12,-1
4,2022-01-03 10:13:00,"101,72","101,89","101,94","101,72",49619,56,106695,106885,106910,106695,590,102,13,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24133,2022-03-18 15:58:00,"110,56","110,54","110,57","110,52",32139,164,115585,115545,115585,115525,215,32,58,-1
24134,2022-03-18 15:59:00,"110,53","110,54","110,57","110,53",7683,121,115530,115550,115560,115530,110,20,59,-1
24135,2022-03-18 16:00:00,"110,53","110,54","110,56","110,53",10303,115,115545,115545,115570,115540,200,36,0,0
24136,2022-03-18 16:01:00,"110,54","110,55","110,55","110,52",6470,68,115540,115540,115550,115525,85,15,1,-1
24137,2022-03-18 16:02:00,"110,55","110,49","110,56","110,49",13040,170,115555,115545,115560,115535,70,10,2,-1