In [77]:
import sys

sys.path.insert(0,r'C:/Users/joao.ramalho/Repositorio-jv/tasks/')

from utils.b3 import b3_utils
import datetime
import pandas as pd
import psycopg2.extras
import psycopg2
import workdays

import pyodbc
import sqlalchemy as sa
import urllib
holidays_br = workdays.load_holidays("BR")

In [78]:
dt = datetime.date.today()
dt_1 = workdays.workday(dt, -1, holidays_br)

In [3]:
CORPORATE_DSN_CONNECTION_STRING = "DSN=Kapitalo_Corp"

In [108]:
# query  = """CALL up2data.XSP_UP2DATA_DEFAULT("""+ dt_1.strftime('%Y-%m-%d') + ", 'Equities_AssetLoanFileV2',"+ """ 'MktNm':'Balcao' """ +")"

In [138]:
CORPORATE_DSN_CONNECTION_STRING = "DSN=Kapitalo_Corp"

connection = pyodbc.connect(CORPORATE_DSN_CONNECTION_STRING)





aux = '"MktNm":"Balcao"'



df = pd.read_sql(f" CALL up2data.XSP_UP2DATA_DEFAULT('{dt_1.strftime('%Y-%m-%d')}', 'Equities_AssetLoanFileV2', '{aux}' )",connection)
df.columns =[x.lower() for x in df.columns]

connection.close()

In [139]:
df

,rptdt,tckrsymb,sctyid,sctysrc,mktidrcd,isin,asst,qtyctrctsday,qtyshrday,valctrctsday,dnrminrate,dnravrgrate,dnrmaxrate,takrminrate,takravrgrate,takrmaxrate,mkt,mktnm,datasts
0,2022-11-30,A1LL34,200000988448,8,BVMF,BRA1LLBDR007,A1LL,2,281,14614.81,12,12,12,12,12,12,91,Balcao,I
1,2022-11-30,A1MD34,200001001301,8,BVMF,BRA1MDBDR002,A1MD,3,4600,224572,5,5,5,5,5,5,91,Balcao,I
2,2022-11-30,A1MP34,200000982637,8,BVMF,BRA1MPBDR006,A1MP,1,1,429.42,12,12,12,12,12,12,91,Balcao,I
3,2022-11-30,A1MT34,200001004835,8,BVMF,BRA1MTBDR008,A1MT,2,4,219.2,12,12,12,12,12,12,91,Balcao,I
4,2022-11-30,A1TH34,200000815394,8,BVMF,BRA1THBDR008,A1TH,1,20,288.2,12,12,12,12,12,12,91,Balcao,I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
803,2022-11-30,WEST3,200000528203,8,BVMF,BRWESTACNOR3,WEST,5,108099,92965.14,1.92,2.74,2.75,1.92,2.74,2.75,93,Eletronico D+1,I
804,2022-11-30,WIZS3,200000841915,8,BVMF,BRWIZSACNOR1,WIZS,1,6600,51348,2.18,2.18,2.18,2.18,2.18,2.18,93,Eletronico D+1,I
805,2022-11-30,XPBR31,200000695518,8,BVMF,BRXPBRBDR001,XPBR,2,6843,594998.85,0.2,1.12,1.13,0.2,1.12,1.13,93,Eletronico D+1,I
806,2022-11-30,YDUQ3,200000847109,8,BVMF,BRYDUQACNOR3,YDUQ,14,245364,2814325.08,10,10.4,10.89,10,10.4,10.89,93,Eletronico D+1,I
807,2022-11-30,Z1OM34,200000480770,8,BVMF,BRZ1OMBDR000,Z1OM,2,7558,114428.12,8,8,8,8,8,8,93,Eletronico D+1,I

In [130]:
df[df['tckrsymb']=='ABEV3']

    tckrsymb takravrgrate
11     ABEV3         1.38
519    ABEV3         1.47
558    ABEV3         1.46