In [132]:
DB_TESTE_HOST = "PGKPTL01"
DB_TESTE_NAME = "db_Teste"
DB_TESTE_USER = "kapitalo11"
DB_TESTE_PASS = "kapitalo11"

import pandas as pd
import psycopg2
import workdays
import matplotlib.pyplot as plt
import plotly.offline as pyo
import plotly.graph_objs as go
# Set notebook mode to work in o
import numpy as np
import pandas as pd
import plotly.graph_objs as go
import psycopg2
import pymongo
from scipy.interpolate import interp1d
import datetime
from matplotlib import pyplot as plt
from IPython.display import Markdown as md
import plotly.express as px
import plotly.graph_objects as go
pd.options.mode.chained_assignment = None  # default='warn'

from matplotlib.ticker import FuncFormatter

import plotly.graph_objects as go




def millions(x, pos):
    """The two args are the value and tick position."""
    #     return 'R${:1.1f}M'.format(x*1e-6)
    return "R${:1.1f}M".format(x * 1e-6)


def mils(x, pos):
    """The two args are the value and tick position."""
    #     return 'R${:1.1f}M'.format(x*1e-6)
    return "R${:1.1f}k".format(x * 1e-3)


formatter = FuncFormatter(millions)
formatter_mils = FuncFormatter(mils)


conn_mongo = pymongo.MongoClient(
    'mongodb://kapitalo11:kapitalo11@192.168.254.20:27017/?authSource=k11')
coll = conn_mongo['k11']['bbgrt']
dt=datetime.date.today()
holidays_b3 = workdays.load_holidays("B3")
holidays_br = workdays.load_holidays("BR")
dt_1=workdays.workday(dt,-1,holidays_b3)
dt_2=workdays.workday(dt,-2,holidays_b3)
dt_21=workdays.workday(dt,-21,holidays_b3)
db_conn_test = psycopg2.connect(
            host=DB_TESTE_HOST,
            dbname=DB_TESTE_NAME,
            user=DB_TESTE_USER,
            password=DB_TESTE_PASS,
        )

In [160]:
## Termos antecipados
query_ant="select * from tbl_boletasrf where str_mesa='Kapitalo 11.1'  and str_fundo='KAPITALO KAPPA MASTER FIM' and str_mercado='Termo de Acao'  and  dbl_quantidade<0"

query_bol="select * from tbl_boletasrf where str_mesa='Kapitalo 11.1'  and str_fundo='KAPITALO KAPPA MASTER FIM' and str_mercado='Termo de Acao'   and dbl_quantidade>0 and dte_vencimento<'2022-01-01'"

In [161]:
df_bol=pd.read_sql(query_bol,db_conn_test)
series=list()
series=df_bol['str_serie'].unique()
brokers=df_bol['str_corretora'].unique()

df_bol['preco termo']=df_bol['str_serie'].apply(lambda x: float(x.split('-')[3].replace(',','.')))

df_bol['volume negociado']=df_bol['dbl_quantidade']*df_bol['preco termo']

df_bol['prazo init']=df_bol.apply(lambda row: workdays.networkdays(row['dte_dataref'],row['dte_vencimento'],holidays_br),axis=1)


df_bol=df_bol.groupby(['str_corretora','str_serie','dte_dataref','dte_vencimento','dte_data']).sum().reset_index()

# for x in brokers:
#     display(df_bol[df_bol['str_corretora']==x].groupby(['str_corretora','prazo init']).sum()[['volume negociado']])
df_bol

,str_corretora,str_serie,dte_dataref,dte_vencimento,dte_data,dbl_quantidade,dbl_taxa,dbl_preco,int,preco termo,volume negociado,prazo init
0,Agora,"01022019-29042019-27,211529-27,609444",2019-02-01,2019-04-29,2019-02-01,5000.0,1.462304,27.211529,26724,27.609444,138047.2200,58
1,Agora,"01022021-01032021-25,672841-25,729515",2021-02-01,2021-03-01,2021-01-28,5000.0,0.310000,25.672841,402434,25.729515,128647.5750,18
2,Agora,"01022021-24022021-23,484894-23,525006",2021-02-01,2021-02-24,2021-01-28,1000.0,0.260000,23.484894,402437,23.525006,23525.0060,15
3,Agora,"01022021-29032021-5,444844-5,468832",2021-02-01,2021-03-29,2021-01-28,2000.0,0.530000,5.444844,402436,5.468832,10937.6640,38
4,Agora,"01022021-29032021-5,454853-5,478885",2021-02-01,2021-03-29,2021-01-28,2000.0,0.530000,5.454853,402435,5.478885,10957.7700,38
...,...,...,...,...,...,...,...,...,...,...,...,...
65508,XP,"31102019-28112019-29,791813-29,931475",2019-10-31,2019-11-28,2019-10-29,10000.0,0.468794,29.791813,45918,29.931475,299314.7500,19
65509,XP,"31102019-28112019-7,280210-7,314347",2019-10-31,2019-11-28,2019-10-29,1000.0,0.468905,7.280210,45902,7.314347,7314.3470,19
65510,XP,"31102019-30122019-27,387522-27,595648",2019-10-31,2019-12-30,2019-10-29,300.0,0.759931,27.387522,45906,27.595648,8278.6944,40
65511,XP,"31102019-30122019-5,730401-5,773952",2019-10-31,2019-12-30,2019-10-29,4000.0,0.759997,5.730401,45910,5.773952,23095.8080,40
65512,XP,"31102019-30122019-9,654370-9,727744",2019-10-31,2019-12-30,2019-10-29,2000.0,0.760003,9.654370,45904,9.727744,19455.4880,40

In [162]:
df_ant=pd.read_sql(query_ant,db_conn_test)

df_ant['preco termo']=df_ant['str_serie'].apply(lambda x: float(x.split('-')[3].replace(',','.')))
# df_ant['prazo init']=df_ant.apply(lambda row: workdays.networkdays(row['dte_dataref'],row['dte_vencimento'],holidays_br),axis=1)

df_ant['volume_ant']=df_ant['dbl_quantidade']*df_ant['preco termo']

df_ant=df_ant[df_ant['str_serie'].isin(series)]
df_ant['prazo cumprido']=df_ant.apply(lambda row: workdays.networkdays(row['dte_data'],row['dte_vencimento'],holidays_br),axis=1)
df_ant=df_ant.groupby(['str_corretora','str_serie','dte_dataref','dte_vencimento','dte_data']).sum().reset_index()
df_ant['dte_data_ant']=df_ant['dte_data']

In [182]:
df  = df_bol.merge(df_ant,on=['str_corretora','str_serie'],how='left').fillna(0)


# df['prazo init']=df.apply(lambda row: workdays.networkdays(row['dte_dataref'],row['dte_vencimento'],holidays_br),axis=1)

# df=df.groupby(['str_corretora','prazo init','prazo cumprido']).sum().reset_index()[['str_corretora','prazo init','prazo cumprido','volume negociado','volume_ant']]


df['% prazo cumprido']=100*df['prazo cumprido']/df['prazo init']
df['% prazo cumprido']= df.apply(lambda row: 100 if row['dte_data_ant']==0 else row['% prazo cumprido'],axis=1 )
# display(df)
test=df[df['str_corretora']=='Guide']['% prazo cumprido']==None
# display(df.iloc[14426])
# prazo=df[df['% prazo cumprido']!=0]
# prazo=prazo.groupby('str_corretora').agg({'% prazo cumprido':np.mean})
# prazo
# geral=df.groupby('str_corretora').agg({'% prazo cumprido':np.mean,'volume negociado':sum,'volume_ant':sum})

# geral['% antecipado']= abs((geral['volume_ant']/geral['volume negociado']))*100
# geral

14426    False
14427    False
14428    False
14429    False
14430    False
         ...
23573    False
23574    False
23575    False
23576    False
23577    False
Name: % prazo cumprido, Length: 9152, dtype: bool