In [1]:
import pandas as pd
import psycopg2
import config
import sys

sys.path.append("..")

import datetime
import requests, zipfile
import io
import yfinance as yf
from yahoofinancials import YahooFinancials

import DatastreamDSWS as DSWS
from setts import regex
import re

import workdays
holidays_br = workdays.load_holidays('BR')
holidays_b3 = workdays.load_holidays('B3')
cdi =0.1165

dt = datetime.date.today()
vcto_0 = dt.strftime('%d/%m/%Y')
dt_pos = workdays.workday(dt, -1, holidays_br)
dt_1 = workdays.workday(dt, -1, holidays_b3)
dt_2 = workdays.workday(dt, -2, holidays_b3)
dt_2 = workdays.workday(dt, -2, holidays_b3)
dt = datetime.date.today()
dt_1 = workdays.workday(dt, -1, holidays_b3)
db_conn_test = psycopg2.connect(host=config.DB_TESTE_HOST, dbname=config.DB_TESTE_NAME , user=config.DB_TESTE_USER, password=config.DB_TESTE_PASS)

db_conn_risk = psycopg2.connect(
    host=config.DB_RISK_HOST,
    dbname=config.DB_RISK_NAME,
    user=config.DB_RISK_USER,
    password=config.DB_RISK_PASS,
)
months = ["F", "G", "H", "J", "K", "M", "N", "Q", "U", "V", "X", "Z"]
map_str_mercado = {
    "SPT": "Acao",
    "LIS": "Opcao de Acao",
    "VAN": "Opcao Flexivel de Acao",
    "BAR": "Opcao Flexivel de Acao",
}



dt

datetime.date(2022, 8, 19)

In [10]:
query="select * from tbl_termos_rv_onshore where dte_data='2022-05-25' and str_corretora='Ativa'"
df=pd.read_sql(query,db_conn_test)

In [13]:

df['dbl_corretagem_original'].sum()+df['dbl_corretagem_performance'].sum()

2200.0

In [20]:
df['dbl_financeiro_ida'].sum()+df['dbl_financeiro_volta'].sum()*(0.5/100)*(0.99)

2189838.0938755

2205271.49

## Termo

In [ ]:
def find_data(ticker, field):
    conn_mongo = pymongo.MongoClient(
        "mongodb://kapitalo11:kapitalo11@192.168.254.20:27017/?authSource=k11"
    )
    coll = conn_mongo["k11"]["bbgrt"]

    result = coll.find_one({"_id": ticker}, {field: 1})
    try:
        return result[field]
    except Exception:
        return 0

def create_key(row):
    return "BVMF|FUTURE|DI1|" + workdays.workday(
        row["mat"], days=2, holidays=workdays.load_holidays()
    ).strftime("%b%y")

def create_bbg_symbol(ticker, rep, sulf, asst):
    return ticker.replace(asst, rep) + f" {sulf}"
def get_contracts(table, asst, day=None):
    if day is None:
        day = workdays.workday(datetime.date.today(), -1, workdays.load_holidays("B3"))
    conn = ps.connect(
        "host='PGKPTL01' dbname='Risk_DB' user='kapitalo11' password='kapitalo11'"
    )
    query = f"SELECT tckrsymb as symbol, xprtndt as mat FROM b3up2data.{table} where rptdt='{day}' and asst='{asst}'"
    df = pd.read_sql(query, con=conn)
    conn.close()
    return df
def p_c_brl_fixed():
    """
    Field: [taxa_termo,fator,taxa]
    """

    df_contract = pd.DataFrame()
    df_contract = df_contract.append(
        [
            ["F", "Jan"],
            ["G", "Feb"],
            ["H", "Mar"],
            ["J", "Apr"],
            ["K", "May"],
            ["M", "Jun"],
            ["N", "Jul"],
            ["Q", "Aug"],
            ["U", "Sep"],
            ["V", "Oct"],
            ["X", "Nov"],
            ["Z", "Dec"],
        ]
    )
    df_contract.columns = ["code", "contract"]
    query = (
        "SELECT str_codigo as codigo, str_codigoserie as serie, dbl_saquestomaturity as du FROM tbl_ativosbmf where dte_data='"
        + datetime.datetime.today().strftime("%Y-%m-%d")
        + "' and str_codigo='DI1'"
    )
    db_conn = ps.connect(
        "host='PGKPTL01' dbname='db_Teste' user='k_geral' password='Kapitalo@01'"
    )
    df_fut = pd.read_sql(query, con=db_conn)
    db_conn.close()
#     t_selic = selic()
#     next_copom = [d for d in copom if d > date.today()][0]

    df_fut["code"] = df_fut.serie.str.slice(0, 1)
    df_fut = df_fut.merge(df_contract, on="code")
    df_fut["contract"] = df_fut["contract"] + df_fut["serie"].str.slice(1, 3)
    df_fut = df_fut.drop(["code"], axis=1)

    df_fut["key"] = "BVMF|FUTURE|" + df_fut["codigo"] + "|" + df_fut["contract"]
    df_fut = df_fut.drop(["codigo", "contract"], axis=1)
    df_price = get_contracts("interest_rate_futurecontractsinstrumentfile", "DI1")

    df_price["ticker_bbg"] = df_price["symbol"].apply(
        lambda row: create_bbg_symbol(row, "OD", "Comdty", "DI1")
    )
    df_price["key"] = df_price.apply(lambda row: create_key(row), axis=1)
    df_price["last"] = df_price["ticker_bbg"].apply(lambda x: find_data(x, "price"))

    df_fut = df_fut.merge(df_price, on="key").sort_values(by="du")

    df_fut["current_price"] = df_fut["last"]

    df_fut["current_price"] = df_fut["current_price"] / 100
    df_fut["du"] = df_fut["du"] - 1
    df_fut["ajuste"] = 100000 / np.power(
        1 + df_fut["current_price"], df_fut["du"] / 252
    )

    df_fut = df_fut.join(df_fut.shift(1).add_suffix("_ant"))
    df_fut = df_fut.drop(["serie_ant", "current_price_ant"], axis=1)

    df_fut.loc[df_fut.ajuste_ant.isnull(), "ajuste_ant"] = 100000
    df_fut.loc[df_fut.du_ant.isnull(), "du_ant"] = 0

    df_fut["taxa_termo"] = (
        np.power(
            df_fut.ajuste_ant / df_fut.ajuste, 252 / (df_fut["du"] - df_fut["du_ant"])
        )
        - 1
    )
    df_fut["du"] = df_fut["du"].astype(int)
    df_fut["du_ant"] = df_fut["du_ant"].astype(int)

    df_curva_realtime = pd.DataFrame({"du": range(0, df_fut.du.max() + 1, 1)})

    df_curva_realtime = df_curva_realtime.merge(
        df_fut[["du", "taxa_termo"]], on="du", how="left"
    )
    df_curva_realtime = df_curva_realtime.bfill()
    # df_curva_realtime.loc[df_curva_realtime['du'] <= du_until_copom, 'taxa'] = t_selic / 100
    # df_curva_realtime.loc[df_curva_realtime['du'] <= du_until_copom, 'taxa_termo'] = t_selic / 100

    df_curva_realtime["fator"] = np.power(1 + df_curva_realtime["taxa_termo"], 1 / 252)

    df_curva_realtime.loc[0, "fator"] = 1
    df_curva_realtime["fator"] = df_curva_realtime["fator"].cumprod()
    df_curva_realtime["taxa"] = (
        np.power(df_curva_realtime.fator, 252 / df_curva_realtime["du"]) - 1
    )

    df_curva_realtime = df_curva_realtime.iloc[1:]
    df_curva_realtime = df_curva_realtime.set_index("du", drop=True)

    return df_curva_realtime

curva=p_c_brl_fixed()

In [ ]:
def curva_pre(x,df_curve=curva):
    return df_curve.loc[x,"taxa"]

curva_pre(38)
# print(dt)

In [ ]:
import psycopg2 as ps
import pymongo
import numpy as np
def find_data(ticker, field):
    conn_mongo = pymongo.MongoClient(
        "mongodb://kapitalo11:kapitalo11@192.168.254.20:27017/?authSource=k11"
    )
    coll = conn_mongo["k11"]["bbgrt"]

    result = coll.find_one({"_id": ticker}, {field: 1})
    try:
        return result[field]
    except Exception:
        return 0

def create_key_cupom(row):
    return "BVMF|FUTURE|DDI|" + workdays.workday(
        row["mat"], days=2, holidays=workdays.load_holidays()
    ).strftime("%b%y")

def create_bbg_symbol(ticker, rep, sulf, asst):
    return ticker.replace(asst, rep) + f" {sulf}"
def get_contracts(table, asst, day=None):
    if day is None:
        day = workdays.workday(datetime.date.today(), -1, workdays.load_holidays("B3"))
    conn = ps.connect(
        "host='PGKPTL01' dbname='Risk_DB' user='kapitalo11' password='kapitalo11'"
    )
    query = f"SELECT tckrsymb as symbol, xprtndt as mat FROM b3up2data.{table} where rptdt='{day}' and asst='{asst}'"
    df = pd.read_sql(query, con=conn)
    conn.close()

    return df
def curva_cupom():
    """
    Field: [taxa_termo,fator,taxa]
    """
    dt = datetime.date.today()
    dt1 = workdays.workday(dt, +1, holidays_b3)


    df_contract = pd.DataFrame()
    df_contract = df_contract.append(
        [
            ["F", "Jan"],
            ["G", "Feb"],
            ["H", "Mar"],
            ["J", "Apr"],
            ["K", "May"],
            ["M", "Jun"],
            ["N", "Jul"],
            ["Q", "Aug"],
            ["U", "Sep"],
            ["V", "Oct"],
            ["X", "Nov"],
            ["Z", "Dec"],
        ]
    )
    df_contract.columns = ["code", "contract"]
    query = (
        "SELECT str_codigo as codigo, str_codigoserie as serie, dte_vencimento as venc,dbl_saquestomaturity as du FROM tbl_ativosbmf where dte_data='"
        + datetime.datetime.today().strftime("%Y-%m-%d")
        + "' and str_codigo='DDI'"
    )
    db_conn = ps.connect(
        "host='PGKPTL01' dbname='db_Teste' user='k_geral' password='Kapitalo@01'"
    )
    df_fut = pd.read_sql(query, con=db_conn)
    db_conn.close()
    df_fut['venc']= df_fut['venc'].apply(lambda x: workdays.workday(x, -1,holidays_br))
    df_fut['venc']= df_fut['venc'].apply(lambda x: workdays.workday(x, +1,holidays_br))
    df_fut['dc']=df_fut['venc'].apply(lambda x: (x-datetime.date.today()).days)

    df_fut["code"] = df_fut.serie.str.slice(0, 1)
    df_fut = df_fut.merge(df_contract, on="code")
    df_fut["contract"] = df_fut["contract"] + df_fut["serie"].str.slice(1, 3)
    df_fut = df_fut.drop(["code"], axis=1)


    df_fut["key"] = "BVMF|FUTURE|" + df_fut["codigo"] + "|" + df_fut["contract"]
    df_fut = df_fut.drop(["codigo", "contract"], axis=1)
    df_price = get_contracts("interest_rate_futurecontractsinstrumentfile", "DDI")

    df_price["ticker_bbg"] = df_price["symbol"].apply(
        lambda row: create_bbg_symbol(row, "EV", "Curncy", "DDI")
    )
    df_price["key"] = df_price.apply(lambda row: create_key_cupom(row), axis=1)
    df_price["last"] = df_price["ticker_bbg"].apply(lambda x: round(find_data(x, "settle"),3))

    
    df_fut = df_fut.merge(df_price, on="key").sort_values(by="dc")

    df_fut["current_price"] = df_fut["last"]
    
    
    df_fut["current_price"] = df_fut["current_price"] / 100
    df_fut["ajuste"] = round(100000 / (1 + (df_fut["current_price"]*df_fut ['dc']/360)),2)
    df_fut["du"] = df_fut["du"].astype(int)

    df_fut = df_fut.join(df_fut.shift(1).add_suffix("_ant"))
    df_fut = df_fut.drop(["serie_ant", "current_price_ant"], axis=1)

    df_fut.loc[df_fut.ajuste_ant.isnull(), "ajuste_ant"] = 100000
    df_fut.loc[df_fut.du_ant.isnull(), "du_ant"] = 0
    df_fut.loc[df_fut.du.isnull(), "du"] = 0
    
    df_fut["du_ant"] = df_fut["du_ant"].astype(int)
    
    
    df_fut["taxa_termo"] = (
        np.power(
            df_fut.ajuste_ant / df_fut.ajuste, 252 / ((df_fut["du"] - df_fut["du_ant"])+1)
        )
        - 1
    )

    df_fut=df_fut.fillna(0)


    df_curva_realtime = pd.DataFrame({"du": range(0, int(df_fut.du.max()) + 1, 1)})

    df_curva_realtime = df_curva_realtime.merge(
        df_fut[["du", "taxa_termo"]], on="du", how="left"
    )
    df_curva_realtime = df_curva_realtime.bfill()
#     df_curva_realtime.loc[df_curva_realtime['du'] <= du_until_copom, 'taxa'] = t_selic / 100
    # df_curva_realtime.loc[df_curva_realtime['du'] <= du_until_copom, 'taxa_termo'] = t_selic / 100

    df_curva_realtime['data']=df_curva_realtime.apply(lambda row: workdays.workday(dt, +int(row['du']), holidays=holidays_b3 ),axis=1)
    df_curva_realtime["fator"] = np.power(1 + df_curva_realtime["taxa_termo"], 1 / 252)

    df_curva_realtime.loc[0, "fator"] = 1
    df_curva_realtime["fator"] = df_curva_realtime["fator"].cumprod()
    df_curva_realtime["taxa"] = ((df_curva_realtime['fator'])**( 252 / df_curva_realtime["du"]) - 1)


    df_curva_realtime = df_curva_realtime.iloc[1:]
    df_curva_realtime['dc']=df_curva_realtime['data'].apply(lambda x: (x-dt).days)
    df_curva_realtime['spot dc']=df_curva_realtime.apply(lambda row: (((1+row['taxa'])**(row['du']/252))-1)*360/row['dc'],axis=1)

#     print(df_curva_realtime)

    return df_curva_realtime
curve=curva_cupom()

In [79]:
# data=dt_1
def pre_curve_d1(data=dt_1):
    db_conn = psycopg2.connect(
        "host='PGKPTL01' dbname='db_Teste' user='k_geral' password='Kapitalo@01'"
    )
    query = """SELECT p.dte_data as data, a.dbl_saquestomaturity as du, p.dbl_ajusteatual as ajuste 
    FROM tbl_ajustes1 p INNER JOIN tbl_ativosbmf a ON p.dte_data=a.dte_data AND
    p.str_codigo=a.str_codigo AND p.str_serie=a.str_codigoserie
    WHERE p.dte_data='"""

    query = query + data.strftime("%Y-%m-%d")
    query = (
        query
        + "' and p.str_codigo='DI1' AND a.str_mercado='Futuro' AND a.str_codigo='DI1' and a.dte_data='"
    )
    query = (
        query
        + data.strftime("%Y-%m-%d")
        + "' ORDER BY p.dte_data, a.dbl_saquestomaturity"
    )

    df = pd.read_sql(query, con=db_conn)
    db_conn.close()
    # cria curva com dados historicos
    df = df.join(df.shift(1).add_suffix("_ant"))
    df.loc[df["data"] != df["data_ant"], "ajuste_ant"] = 100000
    df.loc[df["data"] != df["data_ant"], "du_ant"] = 0
    df = df.drop(["data_ant"], axis=1)
    df["taxa_termo"] = (
        np.power(df.ajuste_ant / df.ajuste, 252 / (df["du"] - df["du_ant"])) - 1
    )
    df["taxa"] = np.power(100000 / df.ajuste, 252 / df["du"]) - 1
    df["du"] = df["du"].astype(int)
    df["du_ant"] = df["du_ant"].astype(int)
    df_curve = pd.DataFrame({"du": range(0, df.du.max() + 1, 1)})
    df_curve = df_curve.merge(df[["du", "taxa_termo"]], on="du", how="left")
    df_curve = df_curve.bfill()
    df_curve["fator"] = np.power(1 + df_curve["taxa_termo"], 1 / 252)
    df_curve.loc[0, "fator"] = 1
    df_curve["fator"] = df_curve["fator"].cumprod()
    df_curve["taxa"] = np.power(df_curve.fator, 252 / df_curve["du"]) - 1
    df_curve = df_curve.iloc[1:]
    df_curve = df_curve.set_index("du", drop=True)
    return df_curve
pre=df_curve

In [80]:
pre

      taxa_termo     fator      taxa
du
1       0.116461  1.000437  0.116461
2       0.116461  1.000875  0.116461
3       0.116461  1.001312  0.116461
4       0.116461  1.001750  0.116461
5       0.116461  1.002188  0.116461
...          ...       ...       ...
3695    0.119200  5.213374  0.119200
3696    0.119200  5.215704  0.119200
3697    0.119200  5.218035  0.119200
3698    0.119200  5.220368  0.119200
3699    0.119200  5.222701  0.119200

[3699 rows x 3 columns]

In [ ]:
DB_TESTE_HOST = "PGKPTL01"
DB_TESTE_NAME = "db_Teste"
DB_TESTE_USER = "kapitalo11"
DB_TESTE_PASS = "kapitalo11"
import psycopg2

db_conn_test = psycopg2.connect(host=DB_TESTE_HOST, dbname=DB_TESTE_NAME , user=DB_TESTE_USER, password=DB_TESTE_PASS)
# query=f"""SELECT dte_data, str_indicador, dbl_preco FROM public.tbl_indicadores1 where (dte_data='2022-02-02' or dte_data='2022-02-03') and (str_indicador='PTAX USD' or str_indicador='PtaxCupomLimpo')"""
# df=pd.read_sql(query,db_conn_test)

# spot=df[df['str_indicador']=='PtaxCupomLimpo']
# spot=spot[spot['dte_data']==dt_1]

# spot.iloc[0]['dbl_preco']

In [ ]:

def create_str_serie(dte_ref, dte_venc, pc, pv, qtd):
    dte_ref = pd.to_datetime(str(dte_ref))
    dte_venc = pd.to_datetime(str(dte_venc))
    dte_ref = dte_ref.strftime("%d%m%Y")
    dte_venc = dte_venc.strftime("%d%m%Y")
#     pc = pc / qtd
#     pv = pv / qtd
    return "-".join(
        [dte_ref, dte_venc, "{:.6f}".format(pv), "{:.6f}".format(pc)]
    ).replace(".", ",")

In [ ]:
print(dt)
## Pos bradesco
import workdays
import numpy as np
holidays_br= workdays.load_holidays("BR")
query= f"SELECT dte_data, str_fundo, str_mesa, str_estrategia, str_corretora, str_mercado, str_titulo, dte_dataref, dte_vencimento, dbl_quantidade, dbl_taxa, dbl_preco, str_codigo, str_serie, str_origem \
FROM public.tbl_boletasrf where (dte_vencimento='{dt.strftime('%Y-%m-%d')}' or dte_data='{dt.strftime('%Y-%m-%d')}') and str_estrategia= 'Termo Antecipacao'  and dbl_quantidade <0 order by str_titulo ASC "

df=pd.read_sql(query,db_conn_test)

df['data_neg']=df.apply(lambda row: datetime.datetime.strptime(row['str_serie'][0:8],'%d%m%Y') if row['dbl_quantidade']<0 else row['dte_dataref'], axis=1)

df['dt_neg_f']=df['data_neg'].apply(lambda x: workdays.workday(x,-2,holidays_b3))

df['dt_neg_f']=pd.to_datetime(df['dt_neg_f']).apply(lambda x: x.date())

df['chave']=df.apply(lambda row: str(row['str_titulo'][:(len(row['str_titulo'])-1)])+str((row['dt_neg_f']-datetime.date(1900,1,1)).days+2)+str((row['dte_vencimento']-datetime.date(1900,1,1)).days+2),axis=1)


df['valor_liquidacao']=df['dbl_preco']*df['dbl_quantidade']

df=df[['chave','valor_liquidacao']]


df=df.groupby("chave").agg({'valor_liquidacao':sum})

df=df.reset_index()
antecipa=df

display(antecipa)

# antecipa.to_excel("antecipa.xlsx")

query= f"SELECT dt_dataposicao as data, REPLACE(str_descr, ',', '') as codigo,dt_data_emissao as data_neg, dt_data_vcto as vencimento,sum(dbl_quantidade) as quantidade, sum(dbl_valor_mercado) as ValorMercado, (sum(dbl_valor_mercado) / sum(dbl_quantidade)) as PU,(SUM(dbl_pu_emissao * dbl_quantidade) / sum(dbl_quantidade)) as PUEmissao FROM tbl_posicao_bradesco where str_carteira='012979' and dt_dataposicao='{dt_1.strftime('%Y-%m-%d')}' and dbl_quantidade<>0 \
and str_nomegrupo='TERMO DE AÇÕES' \
GROUP BY dt_dataposicao, REPLACE(str_descr, ',', ''), dt_data_emissao, dt_data_vcto ORDER BY dt_data_emissao DESC"

df=pd.read_sql(query,db_conn_test)
display(df)
# df['str_serie']=df.apply(lambda row: create_str_serie(row['data_neg], row['vencimento'], pc, pv, qtd),axis=1)

df['chave']=df.apply(lambda row: str(row['codigo'])+str((row['data_neg']-datetime.date(1900,1,1)).days+2)+str((row['vencimento']-datetime.date(1900,1,1)).days+2),axis=1)


df['du']=df.apply(lambda row: workdays.networkdays(row['data_neg'],row['vencimento'],holidays=holidays_br),axis=1)
df['du_venc']=df.apply(lambda row: workdays.networkdays(dt,row['vencimento'],holidays_br)-1,axis=1)
df['taxa dia']=df.apply(lambda row: (((1/row['puemissao'])**(1/row['du'])) -1) ,axis=1) 
antecipa=antecipa.reset_index()

gerenga=pd.merge(df,antecipa,on='chave',how='left')


gerenga['valor_liquidacao']=gerenga['valor_liquidacao']*-1

df=gerenga
cdi=((1+11.65/100)**(1/252)-1)
cdi=round(cdi,8)

df=df.fillna(0)
df=df[df['quantidade']!=0]
df['pnl']=df.apply(lambda row:(row['valor_liquidacao' ] - (row['valormercado']*row['valor_liquidacao']/row['quantidade']) + row['valormercado']*row['taxa dia']*((row['quantidade']-row['valor_liquidacao'])/row['quantidade']) ) if row['valor_liquidacao']!=0 else row['valormercado']*row['taxa dia'],axis=1)
df['over cdi']= df.apply(lambda row:row['pnl']-(row['valormercado']*cdi),axis=1)


df['taxa pre']=df['du_venc'].apply(lambda x: curva_pre(int(x)) if x!=0 else 0 )
df['pu mercado']= 1 /((1+df['taxa pre'])**(df['du_venc']/252))

df['delta']=df['pu mercado']- df['pu']


df['res mtm']=df['delta']*(df['quantidade']-df['valor_liquidacao'])+ df['valor_liquidacao']-(df['valormercado']*df['valor_liquidacao']/df['quantidade'])

df['over mtm']=df['res mtm']- df['pu']*df['quantidade']*cdi
df
df.to_excel('gerenga_termos.xlsx')

In [ ]:
query3= f"SELECT dte_data, str_fundo, str_mesa, str_estrategia, str_corretora, str_mercado, str_titulo, dte_dataref, dte_vencimento, dbl_quantidade, dbl_taxa, dbl_preco, str_codigo, str_serie, str_origem \
FROM public.tbl_boletasrf where dte_data='{dt_1.strftime('%Y-%m-%d')}' and str_estrategia= 'Termo Antecipacao'  and dbl_quantidade >0 "

trades=pd.read_sql(query3,db_conn_test)



trades['chave']=trades.apply(lambda row: str(row['str_titulo'][:(len(row['str_titulo'])-1)])+str((row['dte_data']-datetime.date(1900,1,1)).days+2)+str((row['dte_vencimento']-datetime.date(1900,1,1)).days+2),axis=1)
# # ['data', 'codigo', 'data_neg', 'vencimento', 'quantidade', 'valormercado', 'pu', 'puemissao']
trades['du']=trades.apply(lambda row: workdays.networkdays(row['dte_data'],row['dte_vencimento'],holidays=holidays_br),axis=1)
trades['dc']=trades.apply(lambda row: (row['dte_vencimento']-row['dte_data']).days,axis=1)
trades['taxa dia']=trades.apply(lambda row: ((row['dbl_taxa']+1)**(1/row['du']))-1 ,axis=1)

# trades['pnl']=trades.apply(lambda )
print(trades)
# trades.to_excel("trades_termo.xlsx")

In [ ]:
query="select * from tbl_boletasrf where  (str_codigo='VALE3T' or str_codigo='BRAP4T') and dbl_quantidade<0"

df=pd.read_sql(query,db_conn_test)
df['preco']=df['str_serie'].apply(lambda x: x.split('-')[3].replace(',', '.'))

df['notional']=df['preco']*df['dbl_l']

In [104]:
import psycopg2 as ps
import pymongo
import numpy as np

def find_data(ticker, field):
    conn_mongo = pymongo.MongoClient(
        "mongodb://kapitalo11:kapitalo11@192.168.254.20:27017/?authSource=k11"
    )
    coll = conn_mongo["k11"]["bbgrt"]

    result = coll.find_one({"_id": ticker}, {field: 1})
    try:
        return result[field]
    except Exception:
        return 0
def curva_pre_realtime():
        def find_data(ticker, field):
            conn_mongo = pymongo.MongoClient(
                "mongodb://kapitalo11:kapitalo11@192.168.254.20:27017/?authSource=k11"
            )
            coll = conn_mongo["k11"]["bbgrt"]

            result = coll.find_one({"_id": ticker}, {field: 1})
            try:
                return result[field]
            except Exception:
                return 0

        def create_key(row):
            return "BVMF|FUTURE|DI1|" + workdays.workday(
                row["mat"], days=2, holidays=workdays.load_holidays()
            ).strftime("%b%y")

        def create_bbg_symbol(ticker, rep, sulf, asst):
            return ticker.replace(asst, rep) + f" {sulf}"
        def get_contracts(table, asst, day=None):
            if day is None:
                day = workdays.workday(datetime.date.today(), -1, workdays.load_holidays("B3"))
            conn = psycopg2.connect(
                "host='PGKPTL01' dbname='Risk_DB' user='kapitalo11' password='kapitalo11'"
            )
            query = f"SELECT tckrsymb as symbol, xprtndt as mat FROM b3up2data.{table} where rptdt='{day}' and asst='{asst}'"
            df = pd.read_sql(query, con=conn)
            conn.close()
            return df
        df_contract = pd.DataFrame()
        df_contract = df_contract.append(
            [
                ["F", "Jan"],
                ["G", "Feb"],
                ["H", "Mar"],
                ["J", "Apr"],
                ["K", "May"],
                ["M", "Jun"],
                ["N", "Jul"],
                ["Q", "Aug"],
                ["U", "Sep"],
                ["V", "Oct"],
                ["X", "Nov"],
                ["Z", "Dec"],
            ]
        )
        df_contract.columns = ["code", "contract"]
        query = (
            "SELECT str_codigo as codigo, str_codigoserie as serie, dbl_saquestomaturity as du FROM tbl_ativosbmf where dte_data='"
            + datetime.datetime.today().strftime("%Y-%m-%d")
            + "' and str_codigo='DI1'"
        )
        db_conn = psycopg2.connect(
            "host='PGKPTL01' dbname='db_Teste' user='k_geral' password='Kapitalo@01'"
        )
        df_fut = pd.read_sql(query, con=db_conn)
        db_conn.close()
    #     t_selic = selic()
    #     next_copom = [d for d in copom if d > date.today()][0]

        df_fut["code"] = df_fut.serie.str.slice(0, 1)
        df_fut = df_fut.merge(df_contract, on="code")
        df_fut["contract"] = df_fut["contract"] + df_fut["serie"].str.slice(1, 3)
        df_fut = df_fut.drop(["code"], axis=1)

        df_fut["key"] = "BVMF|FUTURE|" + df_fut["codigo"] + "|" + df_fut["contract"]
        df_fut = df_fut.drop(["codigo", "contract"], axis=1)
        df_price = get_contracts("interest_rate_futurecontractsinstrumentfile", "DI1")

        df_price["ticker_bbg"] = df_price["symbol"].apply(
            lambda row: create_bbg_symbol(row, "OD", "Comdty", "DI1")
        )
        df_price["key"] = df_price.apply(lambda row: create_key(row), axis=1)
        df_price["last"] = df_price["ticker_bbg"].apply(lambda x: find_data(x, "price"))

        df_fut = df_fut.merge(df_price, on="key").sort_values(by="du")
        df_fut["current_price"] = df_fut["last"]

        df_fut["current_price"] = df_fut["current_price"] / 100
        df_fut["du"] = df_fut["du"] - 1

        
        df_fut["ajuste"] = 100000 / np.power(
            1 + df_fut["current_price"], df_fut["du"] / 252
        )

        df_fut = df_fut.join(df_fut.shift(1).add_suffix("_ant"))
        df_fut = df_fut.drop(["serie_ant", "current_price_ant"], axis=1)

        df_fut.loc[df_fut.ajuste_ant.isnull(), "ajuste_ant"] = 100000
        df_fut.loc[df_fut.du_ant.isnull(), "du_ant"] = 0

        df_fut["taxa_termo"] = (
            np.power(
                df_fut.ajuste_ant / df_fut.ajuste, 252 / (df_fut["du"] - df_fut["du_ant"])
            )
            - 1
        )
        df_fut["du"] = df_fut["du"].astype(int)
        df_fut["du_ant"] = df_fut["du_ant"].astype(int)

        df_curva_realtime = pd.DataFrame({"du": range(0, df_fut.du.max() + 1, 1)})

        df_curva_realtime = df_curva_realtime.merge(
            df_fut[["du", "taxa_termo"]], on="du", how="left"
        )
        df_curva_realtime = df_curva_realtime.bfill()
        df_curva_realtime["fator"] = np.power(1 + df_curva_realtime["taxa_termo"], 1 / 252)

        df_curva_realtime.loc[0, "fator"] = 1
        df_curva_realtime["fator"] = df_curva_realtime["fator"].cumprod()
        df_curva_realtime["taxa"] = (
            np.power(df_curva_realtime.fator, 252 / df_curva_realtime["du"]) - 1
        )

        df_curva_realtime = df_curva_realtime.iloc[1:]
        df_curva_realtime = df_curva_realtime.set_index("du", drop=True)
        display(df_curva_realtime)
        return df_curva_realtime

## Opcoes

In [51]:
def create_str_serie(row):
    expiration_date = row["Inst. Expiry Date"]
    strike = format_number(row["Strike Price"])
    call_or_put = row["Inst. Style"]
    month_letter = months[expiration_date.month - 1]
    year = expiration_date.strftime("%y")
    day = expiration_date.strftime("%d")

    if row["Inst. Model"] == "SPT":
        return row["Inst. Primary Asset Id"] + " BZ EQUITY"

    if row["Inst. Type"] == "LIS":
        return row["Inst. Primary Listed Id"]

    if row["Inst. Model"] == "VAN":
        return f"{month_letter}{year}{day}-{call_or_put}-{strike}".replace(".", ",")

    else:
        strike_barrier = format_number(row["Barrier Strike"])
        # rebate = ("%.4f" % row["Barrier Rebate"]).replace(".", ",")
        rebate = format_number(row["Barrier Rebate"])
        sulfix = "CONT" if "C" == row["Inst. Type"][0] else "DISC"
        barrier_type = to_barrier_type(row["Inst. Type"])
        return f"{month_letter}{year}{day}-{call_or_put}-{strike}-{barrier_type}-{strike_barrier}-{rebate}-{sulfix}".replace(
            ".", ","
        )

def format_number(n):
    n = str(round(n, 10))
    n = re.sub(r"\.?0+$", "", n)
    return n
def to_barrier_type(s):
    try:
        return "K" + s[2] + s[1]
    except Exception:
        return "KOD"

In [34]:

## D1
df=pd.read_excel(f"G:\\Trading\\K11\Market Maker\\Closes\\{dt_1.strftime('%Y%m%d')}.xlsx",sheet_name="Sheet2")

df=df[df['Inst. Model'].isin(["VAN","BAR"])]
df['Inst. Expiry Date'] = df['Inst. Expiry Date'].apply(lambda x: x.date())
df=df[df['Inst. Expiry Date']>=dt]
df['asset']=df['Inst. Name'].apply(lambda x: x.split('_')[0][:4])
df['str_serie']=df.apply(lambda x: create_str_serie(x),axis=1)
df=df.rename(columns={'Mkt. Price':'dbl_pufinal'})
df=df[['str_serie','dbl_pufinal']]

antes=df

In [35]:
## D0
df=pd.read_excel(f"G:\\Trading\\K11\Market Maker\\Closes\\{dt_2.strftime('%Y%m%d')}.xlsx",sheet_name="Sheet2")

df=df[df['Inst. Model'].isin(["VAN","BAR"])]
df['Inst. Expiry Date'] = df['Inst. Expiry Date'].apply(lambda x: x.date())
df=df[df['Inst. Expiry Date']>=dt]
df['asset']=df['Inst. Name'].apply(lambda x: x.split('_')[0][:4])
df['str_serie']=df.apply(lambda x: create_str_serie(x),axis=1)
df=df.rename(columns={'Mkt. Price':'dbl_puanterior'})
df=df[['str_serie','dbl_puanterior']]

pos=df

aux=pos.merge(antes,on='str_serie',how='inner')

In [65]:
query=f"select * from tbl_carteira1 where dte_data='2022-04-01' and str_mercado like '%Opcao%' and str_mesa='Kapitalo 11.1'"

df=pd.read_sql(query,db_conn_test)

gerenga=df.merge(aux,on='str_serie',how='left')
gerenga

,dte_data,str_fundo,str_mesa,str_mercado,str_codigo,str_serie,dbl_lote,str_estrategia,ID,str_origem,dbl_preco,dbl_puanterior,dbl_pufinal
0,2022-04-01,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BOVA,BOVAD108,10000.0,Box_3pontas,67704001,None,None,NaN,NaN
1,2022-04-01,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BOVA,BOVAD109,20100.0,Box_3pontas,67704002,None,None,8.203952,8.059811
2,2022-04-01,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BOVA,BOVAD110,10000.0,Box_3pontas,67704003,None,None,NaN,NaN
3,2022-04-01,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BOVA,BOVAD111,10201.0,Box_3pontas,67704004,None,None,NaN,NaN
4,2022-04-01,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BOVA,BOVAD112,10000.0,Box_3pontas,67704005,None,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,2022-04-01,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao Flexivel de Acao,VIIA3,"K2210-P-13,1",111600.0,MM,67704493,None,None,8.692426,8.844223
319,2022-04-01,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao Flexivel de Acao,VIIA3,"M2228-C-17,32",-2700.0,MM,67704494,None,None,0.000465,0.000146
320,2022-04-01,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao Flexivel de Acao,VIIA3,"M2228-P-17,32",2700.0,MM,67704495,None,None,12.603719,12.737147
321,2022-04-01,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao Flexivel de Acao,WEGE3,"J2213-C-38,06-KOU-52,9-6,16-DISC",-4908.0,MM,67704496,None,None,0.084238,0.029585
322,2022-04-01,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BOVA,BOVAD109,100.0,MM,67704497,None,None,8.203952,8.059811

In [157]:
query = """select * from tbl_carteira1 where dte_data='2022-04-07'  and str_mesa='Kapitalo 11.1' and str_mercado like '%Opcao%' and str_estrategia <>'MM' and str_codigo<>'DOL'"""
serie=pd.read_sql(query,db_conn_test)

serie['str_serie'].tolist()
serie

,dte_data,str_fundo,str_mesa,str_mercado,str_codigo,str_serie,dbl_lote,str_estrategia,ID,str_origem,dbl_preco
0,2022-04-07,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BBDC,BBDCE183,-50000.0,Box_3pontas,68290837,None,None
1,2022-04-07,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BBDC,BBDCE190,-50000.0,Box_3pontas,68290838,None,None
2,2022-04-07,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BBDC,BBDCE206,-28000.0,Box_3pontas,68290839,None,None
3,2022-04-07,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BBDC,BBDCE210,-25000.0,Box_3pontas,68290840,None,None
4,2022-04-07,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BBDC,BBDCE213,-50000.0,Box_3pontas,68290841,None,None
...,...,...,...,...,...,...,...,...,...,...,...
90,2022-04-07,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,VIIA,VIIAQ425,7300.0,Box_3pontas,68290927,None,None
91,2022-04-07,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,PETR,PETRE249,228000.0,Box_4pontas,68290932,None,None
92,2022-04-07,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,PETR,PETRE401,-228000.0,Box_4pontas,68290933,None,None
93,2022-04-07,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,PETR,PETRQ249,-228000.0,Box_4pontas,68290934,None,None
94,2022-04-07,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,PETR,PETRQ401,228000.0,Box_4pontas,68290935,None,None

In [158]:
trades="""select * from tbl_auxboletas1 where str_mesa='Kapitalo 11.1' and str_mercado like '%Opcao%'  and dte_data>'2022-01-01' and (str_estrategia='Box_3pontas')"""

trad=pd.read_sql(trades,db_conn_test)
trad

,dte_data,str_fundo,str_corretora,str_mercado,str_codigo,str_serie,str_chavetrader,dbl_lote,dbl_preco,dbl_pu,...,dbl_lotepucurto,str_serielongo,dbl_lotelongo,dbl_precolongo,dbl_pulongo,dbl_lotepulongo,str_estrategia,str_mesa,ID,str_origem
0,2022-04-06,KAPITALO KAPPA MASTER FIM,Liquidez,Opcao de Acao,VIIA,VIIAE350,Joao Ramalho|55002248,-100.0,0.41,0.41,...,None,None,None,None,None,None,Box_3pontas,Kapitalo 11.1,227728806,
1,2022-04-06,KAPITALO KAPPA MASTER FIM,Liquidez,Opcao de Acao,VIIA,VIIAQ380,Joao Ramalho|55002341,5000.0,0.30,0.30,...,None,None,None,None,None,None,Box_3pontas,Kapitalo 11.1,227730408,
2,2022-04-06,KAPITALO KAPPA MASTER FIM,Liquidez,Opcao de Acao,VIIA,VIIAQ415,Joao Ramalho|55002363,2500.0,0.50,0.50,...,None,None,None,None,None,None,Box_3pontas,Kapitalo 11.1,227728538,
3,2022-04-06,KAPITALO KAPPA MASTER FIM,Liquidez,Opcao de Acao,VIIA,VIIAQ415,Joao Ramalho|55002364,2500.0,0.52,0.52,...,None,None,None,None,None,None,Box_3pontas,Kapitalo 11.1,227728539,
4,2022-04-06,KAPITALO KAPPA MASTER FIM,Liquidez,Opcao de Acao,VIIA,VIIAQ415,Joao Ramalho|55002365,200.0,0.54,0.54,...,None,None,None,None,None,None,Box_3pontas,Kapitalo 11.1,227728540,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,2022-04-05,KAPITALO KAPPA MASTER FIM,Liquidez,Opcao de Acao,VIIA,VIIAQ395,Joao Ramalho|54995407,18800.0,0.30,0.30,...,None,None,None,None,None,None,Box_3pontas,Kapitalo 11.1,227161711,
891,2022-04-05,KAPITALO KAPPA MASTER FIM,Liquidez,Opcao de Acao,VIIA,VIIAQ360,Joao Ramalho|54995393,25000.0,0.17,0.17,...,None,None,None,None,None,None,Box_3pontas,Kapitalo 11.1,227161966,
892,2022-04-05,KAPITALO KAPPA MASTER FIM,Liquidez,Opcao de Acao,VIIA,VIIAQ300,Joao Ramalho|54995387,25000.0,0.06,0.06,...,None,None,None,None,None,None,Box_3pontas,Kapitalo 11.1,227162130,
893,2022-04-05,KAPITALO KAPPA MASTER FIM,Liquidez,Opcao de Acao,VIIA,VIIAE400,Joao Ramalho|54995441,-24900.0,0.41,0.41,...,None,None,None,None,None,None,Box_3pontas,Kapitalo 11.1,227161017,
894,2022-04-05,KAPITALO KAPPA MASTER FIM,Liquidez,Opcao de Acao,VIIA,VIIAE400,Joao Ramalho|54995442,-5100.0,0.42,0.42,...,None,None,None,None,None,None,Box_3pontas,Kapitalo 11.1,227161018,

In [159]:
trad=trad[trad['str_serie'].isin(serie['str_serie'].tolist())]
trad['notional']=trad['dbl_lote']*trad['dbl_preco']

trad=trad.groupby(['str_serie']).sum()

trad['medio']=trad['notional']/trad['dbl_lote']
trad=trad[['dbl_lote','medio']]
trad.to_excel("new_options.xlsx")
trad

           dbl_lote     medio
str_serie
BBDCE183   -50000.0  1.185180
BBDCE190   -50000.0  0.891560
BBDCE206   -28000.0  0.508786
BBDCE210   -25000.0  0.470960
BBDCE213   -50000.0  0.760100
...             ...       ...
VIIAQ405    32000.0  0.446094
VIIAQ410    78300.0  0.432695
VIIAQ415     5200.0  0.511154
VIIAQ420    50000.0  0.539280
VIIAQ425     7300.0  0.582740

[91 rows x 2 columns]

In [69]:
## Real time borrow rates

query=f"select * from aluguel_b3 where dte"

In [151]:
url = f"https://arquivos.b3.com.br/apinegocios/tickerbtb/BBDC4/2022-04-06"
print(f"Ticker: BBDC4")
response = requests.get(url)
operations = response.json()

df=pd.DataFrame(operations['values'],columns=['ticker','qtd','rate','id','type','dt','hour'])
df=df[df['type']==91]
avg_real=round((df['qtd']*(1+df['rate'])).sum()/df['qtd'].sum()-1,3)

print(avg_real)
df=df[['hour','rate','qtd']].sort_values(by='hour',ascending=True)
df

Ticker: BBDC4
0.25

        hour  rate     qtd
76  17:31:02  0.25    9450
28  17:31:29  0.25  293300
27  17:36:23  0.25   53102
26  17:36:32  0.25   12814
24  17:41:29  0.25  280000
23  17:42:25  0.25    3732
22  17:42:27  0.25   24844
21  17:42:28  0.25    4718
20  17:50:03  0.25     700
19  17:51:02  0.25    2621
18  17:51:28  0.25   79679
17  17:51:34  0.25   40548
16  17:51:34  0.25   13317
15  17:51:34  0.25   54824
14  17:51:40  0.25   21700
13  17:51:50  0.25    1605
12  17:51:51  0.25   38400
11  17:51:51  0.25    8736
7   18:06:42  0.25  141600
6   18:12:48  0.25  541846
5   18:12:48  0.25   42014
4   18:20:50  0.25  211921
3   18:20:50  0.25  132917
2   18:20:50  0.25  210962
1   18:20:50  0.25  558000

In [152]:
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
fig = make_subplots(specs=[[{'secondary_y':True}]])

fig.add_trace(go.Bar(x=df['hour'].tolist(),y=df['qtd'].tolist(),name='qtde'),secondary_y=False)
fig.add_trace(go.Scatter(x=df['hour'].tolist(),y=df['rate'].tolist(),name='Taxa'),secondary_y=True)

fig.show()

In [111]:
quer="""SELECT ticker,ts::TIMESTAMP::DATE as dt, ts::time as tt,quantity, rate, id FROM public.aluguel_b3 where mercado=91.0 """
db_conn_k11 = psycopg2.connect(
    "host='PGKPTL01' dbname='K11_DB' user='kapitalo11' password='kapitalo11'"
)

df=pd.read_sql(quer,db_conn_k11)

df['rate']=df['rate']*100


df[df['dt']==dt]

df[df['ticker']=='PETR4']

Empty DataFrame
Columns: [ticker, dt, tt, quantity, rate, id]
Index: []

In [210]:
# r=requests.get(r"https://arquivos.b3.com.br/apinegocios/tickercsvbtb/VIIA3/2022-04-08")
# z = zipfile.ZipFile(io.BytesIO(r.content))
# print(z.extractall())


resp = urlopen(r"https://arquivos.b3.com.br/apinegocios/tickercsvbtb/VIIA3/2022-04-11")
zipfile = ZipFile(BytesIO(resp.read()))
for line in zipfile.open(file).readlines():
    print(line.decode('utf-8'))

NameError: name 'file' is not defined

In [208]:

# url = urlopen((r"https://arquivos.b3.com.br/apinegocios/tickercsvbtb/VIIA3/2022-04-11")
# ZipFile(BytesIO(url.read())
              # my_zip_file= ZipFile(BytesIO(url.read()))
# for contained_file in my_zip_file.namelist():
#         # with open(("unzipped_and_read_" + contained_file + ".file"), "wb") as output:
#         for line in my_zip_file.open(contained_file).readlines():
#             print(line)
#             # output.write(line)

In [217]:
print(get_zip("https://arquivos.b3.com.br/apinegocios/tickercsvbtb/VIIA3/2022-04-11"))

NameError: name 'TextIOWrapper' is not defined

In [184]:
##pre
import psycopg2 as ps
import numpy as np
def pre_curve(data):

    db_conn = ps.connect(
        "host='PGKPTL01' dbname='db_Teste' user='k_geral' password='Kapitalo@01'"
    )
    query = """SELECT p.dte_data as data, a.dbl_saquestomaturity as du, p.dbl_ajusteatual as ajuste 
	FROM tbl_ajustes1 p INNER JOIN tbl_ativosbmf a ON p.dte_data=a.dte_data AND
    p.str_codigo=a.str_codigo AND p.str_serie=a.str_codigoserie
    WHERE p.dte_data='"""

    query = query + data.strftime("%Y-%m-%d")
    query = (
        query
        + "' and p.str_codigo='DI1' AND a.str_mercado='Futuro' AND a.str_codigo='DI1' and a.dte_data='"
    )
    query = (
        query
        + data.strftime("%Y-%m-%d")
        + "' ORDER BY p.dte_data, a.dbl_saquestomaturity"
    )

    df = pd.read_sql(query, con=db_conn)
    db_conn.close()
    # cria curva com dados historicos
    df = df.join(df.shift(1).add_suffix("_ant"))
    df.loc[df["data"] != df["data_ant"], "ajuste_ant"] = 100000
    df.loc[df["data"] != df["data_ant"], "du_ant"] = 0
    df = df.drop(["data_ant"], axis=1)
    df["taxa_termo"] = (
        np.power(df.ajuste_ant / df.ajuste, 252 / (df["du"] - df["du_ant"])) - 1
    )
    df["taxa"] = np.power(100000 / df.ajuste, 252 / df["du"]) - 1
    df["du"] = df["du"].astype(int)
    df["du_ant"] = df["du_ant"].astype(int)
    df_curve = pd.DataFrame({"du": range(0, df.du.max() + 1, 1)})
    df_curve = df_curve.merge(df[["du", "taxa_termo"]], on="du", how="left")
    df_curve = df_curve.bfill()
    df_curve["fator"] = np.power(1 + df_curve["taxa_termo"], 1 / 252)
    df_curve.loc[0, "fator"] = 1
    df_curve["fator"] = df_curve["fator"].cumprod()
    df_curve["taxa"] = np.power(df_curve.fator, 252 / df_curve["du"]) - 1
    df_curve = df_curve.iloc[1:]
    df_curve = df_curve.set_index("du", drop=True)
    return df_curve

pre=pre_curve(dt_1)

In [196]:
pre.loc[2,'taxa']

0.11657981457657551

In [1]:

query="select *  FROM b3up2data.equities_assetloanfilev2 where rptdt='2022-04-11' "

df=pd.read_sql(query,db_conn_risk)


# df[df['tckrsymb'][-2:]=='11']
# df[df.loc[:,'tckrsymb'][-2:]=='11']
df['end']=df['tckrsymb'].apply(lambda x: x[-2:])
df=df[df['end']=='11']
df=df[df['mktnm'].isin(['Balcao'])].reset_index()


df=df[['tckrsymb','qtyshrday','takravrgrate']]
df[df['qtyshrday']>100000]
# data["tckrsymb"].isin(["Male"])

NameError: name 'pd' is not defined

In [68]:
query="select * from tbl_carteira1 where dte_data='2022-04-13' and (str_estrategia='Box_3pontas')  and str_mesa='Kapitalo 11.1' and str_mercado='Opcao de Acao'"

df=pd.read_sql(query,db_conn_test)
# df

In [112]:
query="select * from tbl_carteira1 where dte_data='2022-04-13' and (str_estrategia='Box_3pontas')  and str_mesa='Kapitalo 11.1' and str_mercado='Opcao de Acao'"

df=pd.read_sql(query,db_conn_test)

queryb3= "SELECT rptdt, tckrsymb as str_serie,tradgenddt as vencimento,exrcpric as strike,optntp FROM b3up2data.equities_optiononequitiesinstrumentfile_ad where rptdt='2022-04-13' "
opt=pd.read_sql(queryb3,db_conn_risk)

df=df.merge(opt,on='str_serie',how='left')

# df.iloc[0]['vencimento']
df=df[df['vencimento']==datetime.date(2022, 5, 20)]
df['du']=df['vencimento'].apply(lambda x: workdays.networkdays(dt,x),holidays_br )
df=df[df['optntp']=='Put']
df.reset_index()
# df['expo']=df['dbl_lote']*df['strike']

# expo=df['expo'].sum()
# days=df[['du']].drop_duplicates().iloc[0]['du']

# pre=curva_pre_realtime()

,index,dte_data,str_fundo,str_mesa,str_mercado,str_codigo,str_serie,dbl_lote,str_estrategia,ID,str_origem,dbl_preco,rptdt,vencimento,strike,optntp,du
0,7,2022-04-13,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BBDC,BBDCQ183,50200.0,Box_3pontas,69044238,None,None,2022-04-13,2022-05-20,20.67,Put,27
1,8,2022-04-13,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BBDC,BBDCQ190,50100.0,Box_3pontas,69044239,None,None,2022-04-13,2022-05-20,21.17,Put,27
2,9,2022-04-13,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BBDC,BBDCQ206,28000.0,Box_3pontas,69044240,None,None,2022-04-13,2022-05-20,21.92,Put,27
3,10,2022-04-13,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BBDC,BBDCQ210,25300.0,Box_3pontas,69044241,None,None,2022-04-13,2022-05-20,22.17,Put,27
4,11,2022-04-13,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,BBDC,BBDCQ213,50000.0,Box_3pontas,69044242,None,None,2022-04-13,2022-05-20,21.42,Put,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,183,2022-04-13,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,VIIA,VIIAQ405,32400.0,Box_3pontas,69044414,None,None,2022-04-13,2022-05-20,4.05,Put,27
69,184,2022-04-13,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,VIIA,VIIAQ410,79300.0,Box_3pontas,69044415,None,None,2022-04-13,2022-05-20,4.10,Put,27
70,185,2022-04-13,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,VIIA,VIIAQ415,5200.0,Box_3pontas,69044416,None,None,2022-04-13,2022-05-20,4.15,Put,27
71,186,2022-04-13,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,VIIA,VIIAQ420,50000.0,Box_3pontas,69044417,None,None,2022-04-13,2022-05-20,4.20,Put,27
72,187,2022-04-13,KAPITALO KAPPA MASTER FIM,Kapitalo 11.1,Opcao de Acao,VIIA,VIIAQ425,7300.0,Box_3pontas,69044418,None,None,2022-04-13,2022-05-20,4.25,Put,27

In [88]:
pre
# pre.loc[27-1,'fator']

      taxa_termo     fator      taxa
du
1       0.116461  1.000437  0.116461
2       0.116461  1.000875  0.116461
3       0.116461  1.001312  0.116461
4       0.116461  1.001750  0.116461
5       0.116461  1.002188  0.116461
...          ...       ...       ...
3695    0.119200  5.213374  0.119200
3696    0.119200  5.215704  0.119200
3697    0.119200  5.218035  0.119200
3698    0.119200  5.220368  0.119200
3699    0.119200  5.222701  0.119200

[3699 rows x 3 columns]

In [107]:
# di=
# expo



expo/(pre.loc[27-1,'fator'])/()
tax = find_data('ODF24 Comdty', "price")
mat=find_data('ODF24 Comdty', "maturity")

In [65]:
df=pd.read_excel("G:\Trading\K11\Termos\Trades\Guide\KAPITALO_26645_TERMO_28042022 (1).xls")

In [66]:
df.columns=df.iloc[1]

df=df.loc[3:]
df

1,Ticker,Qtd,Preço,Prazo,Taxas,Data de Operação,Data da liquidação,Data de Vencimentos,Valor de Compra,Valor de Venda,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERIADOS
3,PRIO3,100000,26.04,26,0.0093,2022-04-28 00:00:00,2022-05-02 00:00:00,2022-05-24 00:00:00,2604000,2628217.2,...,NaN,2604000,2628217.2,5232217.2,0.95,NaN,NaN,NaN,NaN,1996-02-19 00:00:00
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2078-09-07 00:00:00
1057,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2078-10-12 00:00:00
1058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2078-11-02 00:00:00
1059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2078-11-15 00:00:00
1060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2078-12-25 00:00:00

In [59]:

# df.columns=['ticker','qtd','preço','prazo','taxa','data','liq','volta','compra','venda','vazio','fin compra','fin venda','total','devol']

df.columns=[x for x in range(0,30)]

In [60]:
df=df.drop([10,16,17,18,19,20,25,26,27,28,29,11,12,13,14,15,21,22,23],axis=1)

In [61]:
df

,0,1,2,3,4,5,6,7,8,9,24
3,PRIO3,100000,26.04,26,0.0093,2022-04-28 00:00:00,2022-05-02 00:00:00,2022-05-24 00:00:00,2604000,2628217.2,0.95
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1057,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
df.columns=['ticker','qtd','preço','prazo','taxa','data','liq','volta','compra','venda','devol']

In [67]:
ticker='DI1V23'

In [70]:
ticker[-3:]

'V23'

In [36]:
fin=[
6992.75,
3248.21,
57613.77,
91168.86,
3550.85,
18291.15,
60504.85,
28085.02,
498465.33,
788898.72,
31091.56,
158264.37,
2911067.50,
]

In [37]:
tob_limits = [
    {"min": 0, "max": 135.07, "var": 0, "fixo": 2.7},
    {"min": 135.07, "max": 438.62, "var": 0.02, "fixo": 0},
    {"min": 438.62, "max": 1514.69, "var": 0.015, "fixo": 2.49},
    {"min": 1514.69, "max": 3029.38, "var": 0.01, "fixo": 10.06},
    {"min": 3029.38, "max": float("inf"), "var": 0.005, "fixo": 25.21},
]

In [38]:
def find_corretagem_value(volume, devol=None):
    devol=0.99
    for tarifa in tob_limits:
        if tarifa["min"] < volume and tarifa["max"] >= volume:
            
            return ((tarifa['var'] * volume) + tarifa['fixo']) * (1 - devol)

In [40]:

for x in fin:
    print(find_corretagem_value(x))

0.6017375000000005
0.4145105000000004
3.1327885000000024
4.8105430000000045
0.42964250000000037
1.166657500000001
3.2773425000000027
1.6563510000000017
25.175366500000024
39.69703600000003
1.8066780000000018
8.165318500000009
145.80547500000011

In [10]:
query= f"SELECT  * \
            FROM tbl_gerencialajustes where dte_data>'2022-08-01' and str_mesa ='Kapitalo 11.1' and str_mercado='Futuro' and str_estrategia='CashCarry5' and str_fundo='KAPITALO KAPPA MASTER FIM'"
db_conn_test = psycopg2.connect(host=config.DB_TESTE_HOST, dbname=config.DB_TESTE_NAME , user='k_geral', password='Kapitalo@01')
ga=pd.read_sql(query,db_conn_test)

In [37]:
file = r"C:\Users\joao.ramalho\Downloads\Economatica-8900702928-20220819164905.csv"

df=pd.read_csv(file)

In [38]:
df['Ativo']= df['Ativo'].apply(lambda x: x[0:5])
df['Data']= df['Data'].apply(lambda x: (datetime.datetime.strptime(x,'%Y-%M-%d')).date())

In [47]:
df.loc[df['Ativo']=='PETR4','Data']='a'

In [50]:
df[df['Ativo']=='PETR4']

         Ativo Data Fechamento|ajust p/ prov|Em moeda orig
1084657  PETR4    a                       4.8565945292E-10
1084658  PETR4    a                       4.9994354045E-10
1084659  PETR4    a                       5.2851174957E-10
1084660  PETR4    a                       5.1422762798E-10
1084661  PETR4    a                       5.2565493207E-10
...        ...  ...                                    ...
1094208  PETR4    a                                  31.71
1094209  PETR4    a                                  31.72
1094210  PETR4    a                                  32.01
1094211  PETR4    a                                  32.76
1094212  PETR4    a                                  33.42

[9556 rows x 3 columns]