In [90]:
import pandas as pd
import psycopg2 as ps
import config
import workdays
import datetime
import requests
import yfinance as yf
from yahoofinancials import YahooFinancials
import pymongo
import numpy as np

import DatastreamDSWS as DSWS


cdi =0.1165
holidays_br = workdays.load_holidays('BR')
holidays_b3 = workdays.load_holidays('B3')
dt = datetime.date.today()
vcto_0 = dt.strftime('%d/%m/%Y')
dt_pos = workdays.workday(dt, -1, holidays_br)
dt_1 = workdays.workday(dt, -1, holidays_b3)
dt_2 = workdays.workday(dt, -2, holidays_b3)
dt_2 = workdays.workday(dt, -2, holidays_b3)
dt = datetime.date.today()
dt_1 = workdays.workday(dt, -1, holidays_b3)
db_conn_test = ps.connect(host=config.DB_TESTE_HOST, dbname=config.DB_TESTE_NAME , user=config.DB_TESTE_USER, password=config.DB_TESTE_PASS)

db_conn_risk = ps.connect(
    host=config.DB_RISK_HOST,
    dbname=config.DB_RISK_NAME,
    user=config.DB_RISK_USER,
    password=config.DB_RISK_PASS,
)

In [51]:
def find_data(ticker, field):
    conn_mongo = pymongo.MongoClient(
        "mongodb://kapitalo11:kapitalo11@192.168.254.20:27017/?authSource=k11"
    )
    coll = conn_mongo["k11"]["bbgrt"]

    result = coll.find_one({"_id": ticker}, {field: 1})
    try:
        return result[field]
    except Exception:
        return 0

def create_key(row):
    return "BVMF|FUTURE|DI1|" + workdays.workday(
        row["mat"], days=2, holidays=workdays.load_holidays()
    ).strftime("%b%y")

def create_bbg_symbol(ticker, rep, sulf, asst):
    return ticker.replace(asst, rep) + f" {sulf}"
def get_contracts(table, asst, day=None):
    if day is None:
        day = workdays.workday(datetime.date.today(), -1, workdays.load_holidays("B3"))
    conn = ps.connect(
        "host='PGKPTL01' dbname='Risk_DB' user='kapitalo11' password='kapitalo11'"
    )
    query = f"SELECT tckrsymb as symbol, xprtndt as mat FROM b3up2data.{table} where rptdt='{day}' and asst='{asst}'"
    df = pd.read_sql(query, con=conn)
    conn.close()
    return df
def p_c_brl_fixed():
    """
    Field: [taxa_termo,fator,taxa]
    """

    df_contract = pd.DataFrame()
    df_contract = df_contract.append(
        [
            ["F", "Jan"],
            ["G", "Feb"],
            ["H", "Mar"],
            ["J", "Apr"],
            ["K", "May"],
            ["M", "Jun"],
            ["N", "Jul"],
            ["Q", "Aug"],
            ["U", "Sep"],
            ["V", "Oct"],
            ["X", "Nov"],
            ["Z", "Dec"],
        ]
    )
    df_contract.columns = ["code", "contract"]
    query = (
        "SELECT str_codigo as codigo, str_codigoserie as serie, dbl_saquestomaturity as du FROM tbl_ativosbmf where dte_data='"
        + datetime.datetime.today().strftime("%Y-%m-%d")
        + "' and str_codigo='DI1'"
    )
    db_conn = ps.connect(
        "host='PGKPTL01' dbname='db_Teste' user='k_geral' password='Kapitalo@01'"
    )
    df_fut = pd.read_sql(query, con=db_conn)
    db_conn.close()
#     t_selic = selic()
#     next_copom = [d for d in copom if d > date.today()][0]

    df_fut["code"] = df_fut.serie.str.slice(0, 1)
    df_fut = df_fut.merge(df_contract, on="code")
    df_fut["contract"] = df_fut["contract"] + df_fut["serie"].str.slice(1, 3)
    df_fut = df_fut.drop(["code"], axis=1)

    df_fut["key"] = "BVMF|FUTURE|" + df_fut["codigo"] + "|" + df_fut["contract"]
    df_fut = df_fut.drop(["codigo", "contract"], axis=1)
    df_price = get_contracts("interest_rate_futurecontractsinstrumentfile", "DI1")

    df_price["ticker_bbg"] = df_price["symbol"].apply(
        lambda row: create_bbg_symbol(row, "OD", "Comdty", "DI1")
    )
    df_price["key"] = df_price.apply(lambda row: create_key(row), axis=1)
    df_price["last"] = df_price["ticker_bbg"].apply(lambda x: find_data(x, "price"))

    df_fut = df_fut.merge(df_price, on="key").sort_values(by="du")

    df_fut["current_price"] = df_fut["last"]

    df_fut["current_price"] = df_fut["current_price"] / 100
    df_fut["du"] = df_fut["du"] - 1
    df_fut["ajuste"] = 100000 / np.power(
        1 + df_fut["current_price"], df_fut["du"] / 252
    )

    df_fut = df_fut.join(df_fut.shift(1).add_suffix("_ant"))
    df_fut = df_fut.drop(["serie_ant", "current_price_ant"], axis=1)

    df_fut.loc[df_fut.ajuste_ant.isnull(), "ajuste_ant"] = 100000
    df_fut.loc[df_fut.du_ant.isnull(), "du_ant"] = 0

    df_fut["taxa_termo"] = (
        np.power(
            df_fut.ajuste_ant / df_fut.ajuste, 252 / (df_fut["du"] - df_fut["du_ant"])
        )
        - 1
    )
    df_fut["du"] = df_fut["du"].astype(int)
    df_fut["du_ant"] = df_fut["du_ant"].astype(int)

    df_curva_realtime = pd.DataFrame({"du": range(0, df_fut.du.max() + 1, 1)})

    df_curva_realtime = df_curva_realtime.merge(
        df_fut[["du", "taxa_termo"]], on="du", how="left"
    )
    df_curva_realtime = df_curva_realtime.bfill()
    # df_curva_realtime.loc[df_curva_realtime['du'] <= du_until_copom, 'taxa'] = t_selic / 100
    # df_curva_realtime.loc[df_curva_realtime['du'] <= du_until_copom, 'taxa_termo'] = t_selic / 100

    df_curva_realtime["fator"] = np.power(1 + df_curva_realtime["taxa_termo"], 1 / 252)

    df_curva_realtime.loc[0, "fator"] = 1
    df_curva_realtime["fator"] = df_curva_realtime["fator"].cumprod()
    df_curva_realtime["taxa"] = (
        np.power(df_curva_realtime.fator, 252 / df_curva_realtime["du"]) - 1
    )

    df_curva_realtime = df_curva_realtime.iloc[1:]
    df_curva_realtime = df_curva_realtime.set_index("du", drop=True)

    return df_curva_realtime

curva=p_c_brl_fixed()

In [75]:
def curva_pre(x,df_curve=curva):
    return df_curve.loc[x,"taxa"]

curva_pre(18)

0.11653158025370614

In [91]:
import workdays
import numpy as np
holidays_br= workdays.load_holidays("BR")
query= f"SELECT dte_data, str_fundo, str_mesa, str_estrategia, str_corretora, str_mercado, str_titulo, dte_dataref, dte_vencimento, dbl_quantidade, dbl_taxa, dbl_preco, str_codigo, str_serie, str_origem \
FROM public.tbl_boletasrf where (dte_vencimento='{dt.strftime('%Y-%m-%d')}' or dte_data='{dt.strftime('%Y-%m-%d')}') and str_estrategia= 'Termo Antecipacao'  and dbl_quantidade <0 order by str_titulo ASC "

df=pd.read_sql(query,db_conn_test)

df['data_neg']=df.apply(lambda row: datetime.datetime.strptime(row['str_serie'][0:8],'%d%m%Y') if row['dbl_quantidade']<0 else row['dte_dataref'], axis=1)

df['dt_neg_f']=df['data_neg'].apply(lambda x: workdays.workday(x,-2,holidays_b3))

df['dt_neg_f']=pd.to_datetime(df['dt_neg_f']).apply(lambda x: x.date())

df['chave']=df.apply(lambda row: str(row['str_titulo'][:(len(row['str_titulo'])-1)])+str((row['dt_neg_f']-datetime.date(1900,1,1)).days+2)+str((row['dte_vencimento']-datetime.date(1900,1,1)).days+2),axis=1)


df['valor_liquidacao']=df['dbl_preco']*df['dbl_quantidade']

df=df[['chave','valor_liquidacao','str_serie']]


df=df.groupby("chave").agg({'valor_liquidacao':sum})

df=df.reset_index()
antecipa=df

display(antecipa)

# antecipa.to_excel("antecipa.xlsx")

query= f"SELECT dt_dataposicao as data, REPLACE(str_descr, ',', '') as codigo,dt_data_emissao as data_neg, dt_data_vcto as vencimento,sum(dbl_quantidade) as quantidade, sum(dbl_valor_mercado) as ValorMercado, (sum(dbl_valor_mercado) / sum(dbl_quantidade)) as PU,(SUM(dbl_pu_emissao * dbl_quantidade) / sum(dbl_quantidade)) as PUEmissao FROM tbl_posicao_bradesco where str_carteira='012979' and dt_dataposicao='{dt_1.strftime('%Y-%m-%d')}' and dbl_quantidade<>0 \
and str_nomegrupo='TERMO DE AÇÕES' \
GROUP BY dt_dataposicao, REPLACE(str_descr, ',', ''), dt_data_emissao, dt_data_vcto ORDER BY dt_data_emissao DESC"

df=pd.read_sql(query,db_conn_test)
display(df)
# df['str_serie']=df.apply(lambda row: create_str_serie(row['data_neg], row['vencimento'], pc, pv, qtd),axis=1)

df['chave']=df.apply(lambda row: str(row['codigo'])+str((row['data_neg']-datetime.date(1900,1,1)).days+2)+str((row['vencimento']-datetime.date(1900,1,1)).days+2),axis=1)


df['du']=df.apply(lambda row: workdays.networkdays(row['data_neg'],row['vencimento'],holidays=holidays_br),axis=1)
df['du_venc']=df.apply(lambda row: workdays.networkdays(dt,row['vencimento'],holidays_br)-1,axis=1)
df['taxa dia']=df.apply(lambda row: (((1/row['puemissao'])**(1/row['du'])) -1) ,axis=1) 
antecipa=antecipa.reset_index()

gerenga=pd.merge(df,antecipa,on='chave',how='left')


gerenga['valor_liquidacao']=gerenga['valor_liquidacao']*-1

df=gerenga
cdi=((1+11.65/100)**(1/252)-1)
cdi=round(cdi,8)

df=df.fillna(0)
df=df[df['quantidade']!=0]
df['pnl']=df.apply(lambda row:(row['valor_liquidacao' ] - (row['valormercado']*row['valor_liquidacao']/row['quantidade']) + row['valormercado']*row['taxa dia']*((row['quantidade']-row['valor_liquidacao'])/row['quantidade']) ) if row['valor_liquidacao']!=0 else row['valormercado']*row['taxa dia'],axis=1)
df['over cdi']= df.apply(lambda row:row['pnl']-(row['valormercado']*cdi),axis=1)


df['taxa pre']=df['du_venc'].apply(lambda x: curva_pre(int(x)) if x!=0 else 0 )
df['pu mercado']= 1 /((1+df['taxa pre'])**(df['du_venc']/252))

df['delta']=df['pu mercado']- df['pu']


df['res mtm']=df['delta']*(df['quantidade']-df['valor_liquidacao'])+ df['valor_liquidacao']-(df['valormercado']*df['valor_liquidacao']/df['quantidade'])
df=df[df['valor_liquidacao']!=0]
df['over mtm']=df['res mtm']- df['pu']*df['quantidade']*cdi
df

C:\Users\joao.ramalho\Documents\GitHub\Controle_SnP\workdays.py:74: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  holidays =  [x for x in holidays if x != start_date ]
C:\Users\joao.ramalho\Documents\GitHub\Controle_SnP\workdays.py:45: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  return a <= x <= b or b <= x <= a

               chave  valor_liquidacao
0    AERI34446044641     -2.473853e+04
1    B3SA34457944641     -3.723368e+04
2    BBAS34461044641     -7.616700e+02
3    BBDC44445944641     -6.660168e+04
4    BBDC44446144641     -2.083026e+04
5    BBDC44455044641     -1.591790e+03
6    BBDC44455144641     -7.900449e+05
7    BBDC44460944641     -1.502857e+05
8    BBDC44462444641     -3.978910e+05
9    BEEF34428044641     -1.045868e+04
10  BIDI114449044641     -1.784930e+04
11  BIDI114459444641     -5.186695e+04
12   BIDI44462744643     -2.402440e+03
13  BOVA114457944641     -1.563900e+04
14   BPAN44461044641     -1.504569e+04
15  BRBI114455044641     -3.395700e+03
16   CMIN34446144641     -2.693401e+04
17   CMIN34460944641     -1.545593e+04
18   CSAN34458144641     -8.760588e+04
19   CSNA34455044641     -4.895306e+04
20   CSNA34458044641     -1.012164e+05
21   CSNA34460944641     -5.341281e+05
22   CSNA34461044641     -2.993356e+05
23   CSNA34461344642     -7.597645e+05
24   CVCB34445944641     -2.007781e+06
25   EQPA34428144641     -1.292476e+04
26   ETER34461544676     -6.010330e+05
27   GNDI34459344642     -2.184253e+04
28   GNDI34459544641     -1.432248e+05
29   GNDI34459644642     -1.451279e+04
30   GOAU44459544685     -2.455761e+04
31   GOAU44460944699     -1.776030e+04
32   IRBR34427944641     -1.706025e+06
33   IRBR34458044641     -3.482244e+04
34   LOGN34459544641     -1.619732e+04
35   LPSB34447044650     -1.776262e+04
36   LREN34455144641     -2.792900e+03
37   NTCO34463044676     -2.849518e+05
38   PETR44451944641     -8.670050e+03
39   PETR44460644642     -1.676836e+05
40   PETR44460844642     -1.013310e+05
41   PETR44460944641     -2.995193e+05
42   PRIO34459444641     -5.138402e+04
43   PRIO34462444641     -5.152617e+05
44   RRRP34455144641     -8.144226e+04
45   RRRP34461044641     -4.675908e+04
46  SULA114445944641     -4.177231e+05
47   USIM54460944641     -1.799962e+04
48   VALE34446044641     -1.484186e+05
49   VALE34449044641     -2.309518e+04
50   VALE34454744669     -2.987723e+05
51   VALE34460944641     -1.149259e+05
52   VALE34461444644     -5.677741e+04
53   VAMO34458044641     -5.094900e+04
54   VBBR34460944642     -2.487798e+04

,data,codigo,data_neg,vencimento,quantidade,valormercado,pu,puemissao
0,2022-03-18,BBDC4,2022-03-18,2022-04-19,596497.0,591046.09,0.990862,0.989235
1,2022-03-18,BBDC4,2022-03-18,2022-05-24,151451.0,148428.10,0.980040,0.976123
2,2022-03-18,BIDI4,2022-03-18,2022-09-14,706.0,666.49,0.944037,0.933261
3,2022-03-18,BOAS3,2022-03-18,2022-04-18,94141.0,93321.38,0.991294,0.989626
4,2022-03-18,BOAS3,2022-03-18,2022-05-17,53717.0,52768.71,0.982347,0.981672
...,...,...,...,...,...,...,...,...
1620,2022-03-18,SAPR11,2021-04-01,2022-03-28,28216.0,28142.35,0.997390,0.944944
1621,2022-03-18,IRBR3,2021-03-31,2022-03-28,32048.0,31964.60,0.997398,0.941176
1622,2022-03-18,LUPA3,2021-03-29,2022-03-24,20203.0,20168.28,0.998281,0.949665
1623,2022-03-18,ELET6,2021-03-26,2022-03-21,278989.0,278867.93,0.999566,0.949003
1624,2022-03-18,IRBR3,2021-03-24,2022-03-21,427537.0,427350.55,0.999564,0.949909

,data,codigo,data_neg,vencimento,quantidade,valormercado,pu,puemissao,chave,du,...,taxa dia,index,valor_liquidacao,pnl,over cdi,taxa pre,pu mercado,delta,res mtm,over mtm
162,2022-03-18,NTCO3,2022-03-10,2022-04-25,284951.0,281976.85,0.989563,0.984083,NTCO34463044676,31,...,0.000518,37.0,2.849518e+05,2974.157444,2850.823589,0.116537,0.989990,0.000427,2974.157508,2850.823653
235,2022-03-18,BIDI4,2022-03-07,2022-03-23,2402.0,2399.29,0.998872,0.994932,BIDI44462744643,13,...,0.000391,12.0,2.402440e+03,2.710325,1.660899,0.116500,0.999126,0.000254,2.710385,1.660959
409,2022-03-18,ETER3,2022-02-23,2022-04-25,601033.0,594758.20,0.989560,0.982539,ETER34461544676,40,...,0.000440,26.0,6.010330e+05,6274.800000,6014.658711,0.116537,0.989990,0.000430,6274.800000,6014.658711
450,2022-03-18,VALE3,2022-02-22,2022-03-24,56777.0,56678.20,0.998260,0.990213,VALE34461444644,21,...,0.000468,52.0,5.677741e+04,98.800522,74.010044,0.116500,0.998689,0.000429,98.800538,74.010060
458,2022-03-18,CSNA3,2022-02-21,2022-03-22,759764.0,759100.35,0.999127,0.990017,CSNA34461344642,20,...,0.000502,23.0,7.597645e+05,663.650179,331.627277,0.116500,0.999563,0.000436,663.650210,331.627308
473,2022-03-18,BBAS3,2022-02-18,2022-03-21,57286.0,57261.07,0.999565,0.990702,BBAS34461044641,20,...,0.000467,2.0,7.616700e+02,26.725840,1.680421,0.000000,1.000000,0.000435,24.930000,-0.115419
479,2022-03-18,BPAN4,2022-02-18,2022-03-21,23748.0,23737.96,0.999577,0.991978,BPAN44461044641,20,...,0.000403,14.0,1.504569e+04,9.864748,-0.517998,0.000000,1.000000,0.000423,10.040000,-0.342746
543,2022-03-18,GOAU4,2022-02-17,2022-05-18,44704.0,43893.70,0.981874,0.972616,GOAU44460944699,61,...,0.000455,31.0,1.776030e+04,333.966111,314.767445,0.119260,0.982275,0.000401,332.726444,313.527779
574,2022-03-18,VALE3,2022-02-17,2022-03-21,88111.0,88072.92,0.999568,0.990213,VALE34460944641,21,...,0.000468,51.0,1.149259e+05,37.112429,-1.409785,0.000000,1.000000,0.000432,38.080000,-0.442214
578,2022-03-18,VBBR3,2022-02-17,2022-03-22,24877.0,24856.23,0.999165,0.989723,VBBR34460944642,22,...,0.000470,54.0,2.487798e+04,20.770358,9.898492,0.116500,0.999563,0.000398,20.770428,9.898562
600,2022-03-18,PETR4,2022-02-16,2022-03-22,101331.0,101242.42,0.999126,0.988551,PETR44460844642,23,...,0.000501,40.0,1.013310e+05,88.580000,44.297578,0.116500,0.999563,0.000437,88.580000,44.297578
637,2022-03-18,PETR4,2022-02-14,2022-03-22,167683.0,167537.00,0.999129,0.987576,PETR44460644642,25,...,0.000500,39.0,1.676836e+05,146.000215,72.721207,0.116500,0.999563,0.000433,146.000254,72.721245
723,2022-03-18,GNDI3,2022-02-04,2022-03-22,14512.0,14500.10,0.999180,0.984372,GNDI34459644642,31,...,0.000508,29.0,1.451279e+04,11.900246,5.558048,0.116500,0.999563,0.000383,11.900345,5.558146
748,2022-03-18,GNDI3,2022-02-03,2022-03-21,143224.0,143162.23,0.999569,0.984664,GNDI34459544641,31,...,0.000499,28.0,1.432248e+05,61.769943,-0.847784,0.000000,1.000000,0.000431,61.770000,-0.847728
749,2022-03-18,GOAU4,2022-02-03,2022-05-04,24557.0,24225.47,0.986500,0.969227,GOAU44459544685,61,...,0.000513,30.0,2.455761e+04,331.537927,320.941949,0.117376,0.986875,0.000375,331.538007,320.942028
780,2022-03-18,GNDI3,2022-02-01,2022-03-22,21842.0,21823.44,0.999150,0.982924,GNDI34459344642,34,...,0.000507,27.0,2.184253e+04,18.560182,9.014828,0.116500,0.999563,0.000413,18.560232,9.014877
960,2022-03-18,BOVA11,2022-01-18,2022-03-21,192869.0,192785.12,0.999565,0.979368,BOVA114457944641,43,...,0.000485,13.0,1.563900e+04,92.711160,8.388876,0.000000,1.000000,0.000435,83.880000,-0.442284
1160,2022-03-18,VALE3,2021-12-17,2022-04-18,828083.0,820872.52,0.991293,0.963355,VALE34454744669,84,...,0.000445,50.0,2.987723e+05,2834.796660,2475.755228,0.116533,0.991724,0.000431,2829.681798,2470.640367
1453,2022-03-18,LPSB3,2021-10-01,2022-03-30,17762.0,17700.60,0.996543,0.959681,LPSB34447044650,124,...,0.000332,35.0,1.776262e+04,61.401938,53.659873,0.116500,0.996944,0.000400,61.401895,53.659830
1467,2022-03-18,CMIN3,2021-09-22,2022-03-21,130778.0,130721.40,0.999567,0.960052,CMIN34446144641,124,...,0.000329,16.0,2.693401e+04,45.788580,-11.387653,0.000000,1.000000,0.000433,56.600000,-0.576233
1470,2022-03-18,VALE3,2021-09-21,2022-03-21,86750.0,86712.60,0.999569,0.959846,VALE34446044641,125,...,0.000328,48.0,1.484186e+05,43.773738,5.846514,0.000000,1.000000,0.000431,37.400000,-0.527224
1624,2022-03-18,IRBR3,2021-03-24,2022-03-21,427537.0,427350.55,0.999564,0.949909,IRBR34427944641,250,...,0.000206,32.0,1.706025e+06,481.285857,294.367000,0.000000,1.000000,0.000436,186.450000,-0.468857

In [116]:
##Posicao Bradesco

query= f"SELECT dt_dataposicao as data, REPLACE(str_descr, ',', '') as codigo,dt_data_emissao as data_neg, dt_data_vcto as vencimento,sum(dbl_quantidade) as quantidade, sum(dbl_valor_mercado) as ValorMercado, (sum(dbl_valor_mercado) / sum(dbl_quantidade)) as PU,(SUM(dbl_pu_emissao * dbl_quantidade) / sum(dbl_quantidade)) as PUEmissao FROM tbl_posicao_bradesco where str_carteira='012979' and dt_dataposicao='{dt_1.strftime('%Y-%m-%d')}' and dbl_quantidade<>0 \
and str_nomegrupo='TERMO DE AÇÕES' \
GROUP BY dt_dataposicao, REPLACE(str_descr, ',', ''), dt_data_emissao, dt_data_vcto ORDER BY codigo ASC"

df=pd.read_sql(query,db_conn_test)
display(df)
# df['str_serie']=df.apply(lambda row: create_str_serie(row['data_neg], row['vencimento'], pc, pv, qtd),axis=1)

df['chave']=df.apply(lambda row: str(row['codigo'])+str((row['data_neg']-datetime.date(1900,1,1)).days+2)+str((row['vencimento']-datetime.date(1900,1,1)).days+2),axis=1)


df['du']=df.apply(lambda row: workdays.networkdays(row['data_neg'],row['vencimento'],holidays=holidays_br),axis=1)
df['du_venc']=df.apply(lambda row: workdays.networkdays(dt,row['vencimento'],holidays_br)-1,axis=1)
df['taxa dia']=df.apply(lambda row: (((1/row['puemissao'])**(1/row['du'])) -1) ,axis=1) 


df.to_excel("brad_termo.xlsx")

,data,codigo,data_neg,vencimento,quantidade,valormercado,pu,puemissao
0,2022-03-18,ABEV3,2021-05-27,2022-05-23,538808.0,528299.33,0.980496,0.942062
1,2022-03-18,ABEV3,2021-06-17,2022-06-13,607148.0,591084.97,0.973543,0.935988
2,2022-03-18,ABEV3,2021-07-20,2022-07-15,108165.0,104138.84,0.962778,0.934684
3,2022-03-18,ABEV3,2021-07-28,2022-07-25,59843.0,57447.31,0.959967,0.926968
4,2022-03-18,ABEV3,2021-08-02,2022-07-28,1978832.0,1896804.19,0.958547,0.932152
...,...,...,...,...,...,...,...,...
1620,2022-03-18,XPBR31,2021-11-09,2022-11-04,33695.0,31229.31,0.926823,0.886218
1621,2022-03-18,XPBR31,2021-12-22,2022-06-20,2288.0,2223.61,0.971858,0.941611
1622,2022-03-18,XPBR31,2022-02-14,2022-08-15,56855.0,54175.00,0.952863,0.939675
1623,2022-03-18,XPBR31,2022-03-07,2022-05-06,4184476.0,4124023.13,0.985553,0.979368
1624,2022-03-18,XPBR31,2022-03-10,2022-06-08,6142.0,5989.09,0.975104,0.967540

In [117]:
query= f"SELECT * from tbl_carteira1 where dte_data='{dt_1.strftime('%Y-%m-%d')}' and str_estrategia= 'Termo Antecipacao'"
df_c=pd.read_sql(query,db_conn_test)
df_c
df_c['data_neg_p']=df_c.apply(lambda row:datetime.datetime.strptime(row['str_serie'][0:8],'%d%m%Y'), axis=1)
df_c['data_neg']=df_c['data_neg_p'].apply(lambda x: workdays.workday(x,-2,holidays_b3).date())

# df['dt_neg_f']=pd.to_datetime(df['dt_neg_f']).apply(lambda x: x.date())


df_c['codigo']=df_c['str_codigo'].apply(lambda x: x.replace('T',''))

df_c.to_excel('carteira_termo_2.xlsx')

C:\Users\joao.ramalho\Documents\GitHub\Controle_SnP\workdays.py:74: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  holidays =  [x for x in holidays if x != start_date ]
C:\Users\joao.ramalho\Documents\GitHub\Controle_SnP\workdays.py:45: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  return a <= x <= b or b <= x <= a

In [118]:
compara=df.merge(df_c,on=['codigo','data_neg'],how='left')

compara.to_excel("comparacao_termos.xlsx")

In [113]:
compara

,data,codigo,data_neg,vencimento,quantidade,valormercado,pu,puemissao,chave,du,...,str_mesa,str_mercado,str_codigo,str_serie,dbl_lote,str_estrategia,ID,str_origem,dbl_preco,data_neg_p
0,2022-03-18,ABEV3,2021-05-27,2022-05-23,538808.0,528299.33,0.980496,0.942062,ABEV34434344704,249,...,Kapitalo 11.1,Termo de Acao,ABEV3T,"31052021-23052022-17,384385-18,389376",29300.0,Termo Antecipacao,66285780,None,None,2021-05-31
1,2022-03-18,ABEV3,2021-06-17,2022-06-13,607148.0,591084.97,0.973543,0.935988,ABEV34436444725,250,...,Kapitalo 11.1,Termo de Acao,ABEV3T,"21062021-13062022-19,234067-20,442696",29700.0,Termo Antecipacao,66285776,None,None,2021-06-21
2,2022-03-18,ABEV3,2021-07-20,2022-07-15,108165.0,104138.84,0.962778,0.934684,ABEV34439744757,250,...,Kapitalo 11.1,Termo de Acao,ABEV3T,"22072021-15072022-17,173543-18,333180",5900.0,Termo Antecipacao,66285778,None,None,2021-07-22
3,2022-03-18,ABEV3,2021-07-28,2022-07-25,59843.0,57447.31,0.959967,0.926968,ABEV34440544767,250,...,Kapitalo 11.1,Termo de Acao,ABEV3T,"30072021-25072022-17,320150-18,701210",3200.0,Termo Antecipacao,66285779,None,None,2021-07-30
4,2022-03-18,ABEV3,2021-08-02,2022-07-28,1978832.0,1896804.19,0.958547,0.932152,ABEV34441044770,250,...,Kapitalo 11.1,Termo de Acao,ABEV3T,"04082021-28072022-17,128219-18,407740",107500.0,Termo Antecipacao,66285771,None,None,2021-08-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1934,2022-03-18,XPBR31,2021-11-09,2022-11-04,33695.0,31229.31,0.926823,0.886218,XPBR314450944869,250,...,Kapitalo 11.1,Termo de Acao,XPBR31T,"11112021-04112022-188,217185-210,606570",100.0,Termo Antecipacao,66287418,None,None,2021-11-11
1935,2022-03-18,XPBR31,2021-12-22,2022-06-20,2288.0,2223.61,0.971858,0.941611,XPBR314455244732,124,...,Kapitalo 11.1,Termo de Acao,XPBR31T,"24122021-20062022-167,380669-176,033077",13.0,Termo Antecipacao,66287421,None,None,2021-12-24
1936,2022-03-18,XPBR31,2022-02-14,2022-08-15,56855.0,54175.00,0.952863,0.939675,XPBR314460644788,126,...,Kapitalo 11.1,Termo de Acao,XPBR31T,"16022022-15082022-175,444383-186,410000",305.0,Termo Antecipacao,66287420,None,None,2022-02-16
1937,2022-03-18,XPBR31,2022-03-07,2022-05-06,4184476.0,4124023.13,0.985553,0.979368,XPBR314462744687,43,...,Kapitalo 11.1,Termo de Acao,XPBR31T,"09032022-06052022-137,043606-139,482560",30000.0,Termo Antecipacao,66287416,None,None,2022-03-09
1938,2022-03-18,XPBR31,2022-03-10,2022-06-08,6142.0,5989.09,0.975104,0.967540,XPBR314463044720,63,...,Kapitalo 11.1,Termo de Acao,XPBR31T,"14032022-08062022-157,285849-161,657632",38.0,Termo Antecipacao,66287419,None,None,2022-03-14

In [89]:
pl=pd.read_excel("C:\\Users\\joao.ramalho\\Documents\\GitHub\\portfolio\\cache\\pl_cache.xlsx")
# pl=pl.reset_index('str_fundo',inplace=True)
x='KAPITALO KAPPA MASTER FIM'
print(pl[pl['str_fundo']==x].iloc[0]['dbl_plpactual'])

2209891700.74195